apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kustomize.config.k8s.io/id: |
      group: apps
      kind: Deployment
      name: nginx-deployment
      version: v1
  labels:
    app: hello
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - image: 7777
          name: nginx
