apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  annotations:
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: registry.hub.docker.com/library/nginx:perl
          ports:
            - containerPort: 80
