apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: hello
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - image: registry.hub.docker.com/library/nginx:1.19.10
          name: nginx
